version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.2.4/terraform_1.2.4_linux_amd64.zip"
      - "unzip terraform_1.2.4_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - cd s3
      - terraform init
      - cd ../lambda
      - terraform init
      - cd ../
  build:
    commands:
      - cd s3
      - terraform apply -auto-approve
      - cd ../lambda
      - terraform apply -auto-approve
      - cd ../
  post_build:
    commands:
      - echo terraform apply on `date`
